#!/bin/sh
# used resources:
# https://en.wikipedia.org/wiki/ANSI_escape_code

VERSION="0.2.0"

export RESETER="\033[0m"
export SOURCE_FILE="/dev/stdin"

die(){
  echo "Error: $1" >"/dev/stderr"
  exit 1
}

print_version(){
  cat >>"/dev/stdout" <<EOF
shclrz - colorizing output in the shell
v$VERSION
EOF
  exit 0
}

cleanup(){
  rm "$DIALOG_FILE"
}

print_help(){
  cat >>"/dev/stdout" <<EOF
Description: colorizing output in the shell

Usage: shclrz [ -h | --help ]
              [ -v | --version ]
              [ -i | --info ]
              [ -s | --source-file  SOURCE_FILE ]
              [ -b | --background   COLOR ]
              [ -f | --foreground   COLOR ]
              [ -F | --formatting   OPTION ]

Note:
  not all formatting options are supported by all terminals

List of colors:
  black         blue
  red           magenta
  green         cyan
  yellow        white

Formatting options:
  bold          dim
  italic        underline

EOF
  [ -z "$1" ] \
    && exit 0 \
    || exit "$1"
}

print_info(){
  echo "colors:
  \033[40mblack       0\033[0m
  \033[41mred         1\033[0m
  \033[42mgreen       2\033[0m
  \033[43myellow      3\033[0m
  \033[44mblue        4\033[0m
  \033[45mmagenta     5\033[0m
  \033[46mcyan        6\033[0m
  \033[47;30mwhite       7\033[0m

formatting:
  \033[1mbold        1\033[0m
  \033[2mdim         2\033[0m
  \033[3mitalic      3\033[0m
  \033[4munderline   4\033[0m"
  exit 0
}

get_color(){
  case "$1" in
    black)      echo -n "0" ;;
    red)        echo -n "1" ;;
    green)      echo -n "2" ;;
    yellow)     echo -n "3" ;;
    blue)       echo -n "4" ;;
    magenta)    echo -n "5" ;;
    cyan)       echo -n "6" ;;
    white)      echo -n "7" ;;
    *) die "invalid color" ;;
  esac
}

get_formatting(){
  case "$1" in
    bold)       echo -n "1" ;;
    dim)        echo -n "2" ;;
    italic)     echo -n "3" ;;
    underline)  echo -n "4" ;;
    *) die "invalid formatting" ;;
  esac
}

print_formatted(){
  if [ ! -z "$FORMATTING" ]; then
    prefix="$FORMATTING"
  fi
  if [ ! -z "$FOREGROUND_COLOR" ]; then
    [ -z "$prefix" ] \
      && prefix="3$FOREGROUND_COLOR" \
      || prefix="$prefix;3$FOREGROUND_COLOR"
  fi
  if [ ! -z "$BACKGROUND_COLOR" ]; then
    [ -z "$prefix" ] \
      && prefix="4$BACKGROUND_COLOR" \
      || prefix="$prefix;4$BACKGROUND_COLOR"
  fi
  [ -z "$prefix" ] && prefix="0"
  echo -n "\033[${prefix}m"
  cat "$SOURCE_FILE"
  echo -n "$RESETER"
}

PARSED_ARGS="$(getopt -a -n shclrz -o "hvb:f:s:F:i" --long "help,version,background:,foreground:,source-file:,formatting:,info" -- "$@")"
VALID_ARGS=$?
[ "$VALID_ARGS" = 0 ] || print_help 1
eval set -- "$PARSED_ARGS"

while :
do
  case "$1" in
    -h | --help )
      print_help; shift ;;
    -v | --version )
      print_version; shift ;;
    -b | --background )
      export BACKGROUND_COLOR="$(get_color "$2")" ; shift 2 ;;
    -f | --foreground )
      export FOREGROUND_COLOR="$(get_color "$2")" ; shift 2 ;;
    -F | --formatting )
      export FORMATTING="$(get_formatting "$2")" ; shift 2 ;;
    -s | --source-file )
      export SOURCE_FILE="$2" ; shift 2 ;;
    -i | --info )
      print_info ;;
    --)
      shift; break ;;
    *)
      die "invalid arguments passed" ;;
  esac
done

print_formatted

