.TH "shclrz" "1" 

.SH "NAME"
.PP
shclrz - colorizing output in the shell

.SH "SYNOPSIS"
.PP
shclrz [OPTIONS]

.SH "DESCRIPTION"
.PP
shclrz (as in SHell CoLoRiZer) is a simple shell script with the goal to simplify creating colorful output in the shell.

.SH "OPTIONS"
.SS "-h, --help"
.PP
Print help.
.SS "-v, --version"
.PP
Print program version.
.SS "-g, --generate"
.PP
Generate ANSI sequence
.SS "-s [SOURCE_FILE], --source-file [SOURCE_FILE]"
.PP
Read from SOURCE_FILE instead of stdin
.SS "-f [COLOR], --foreground [COLOR]"
.PP
Specify foreground color
.SS "-b [COLOR], --background [COLOR]"
.PP
Specify background color
.SS "-F [OPTION], --formatting [OPTION]"
.PP
Use a formatting option like bold, italic or underline

.SH "EXAMPLES"
.SS "shclrz -g"
.PP
Opens an interactive menu to select the background/foreground color and enter the text. Returns a string which contains the ANSI color sequence for chosen color and text.
.SS "shclrz -f red <file.txt"
.PP
Outputs the content of file.txt with red foreground.
.SS "ls | shclrz -b blue"
.PP
Colors the output of ls with blue background.

.SH "AUTHOR"
.PP
alexcoder04 (\fIhttps://github.com/alexcoder04/shclrz\fP)

